### PR TITLE
Adding Fake Companies and Programming Language lists

### PR DESCRIPTION
**Pull request by demersdesigns**
Hi,
These are two lists that I had in a project that I had started to create that is really similar to yours. Hopefully, they can be added to the site. Let me know if there are any concerns with the formatting, etc.

Thanks!
Paul

### CODE REVIEW

**Comment by vltrajvlien** [comment]
Thanks a lot @demersdesigns for your contribution 💯 
Sorry for the late reply, I was on vacation. I'll include your lists in this week's release on https://lists.design
Cheers!

**Comment by demersdesigns** [comment]
Glad to help out! Love this idea! I'd actually love to see this as a Sketch plugin. The Craft plugin from InVision handles this, but the way to add custom lists is super clunky.

**Comment by vltrajvlien** [comment]
@demersdesigns I'd love that. Adding @AntoineWattier, who's helping with the dev. It's a side project, so we're moving quite slowly, but having a Sketch plugin at some point is definitely something we're thinking about.

**Comment by demersdesigns** [comment]
@jperriere @AntoineWattier Definitely let me know if I can help in any way. I am just getting started with Sketch plugins, but would love to get something going.

**Pull request merged**
